site_name: Prefeitura de Passo Fundo
site_url: https://interacao-humano-computador.github.io/2021.2-Prefeitura-de-Passo-Fundo/

# Repository
repo_name: Prefeitura de Passo Fundo 
repo_url: https://github.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo

nav:
 - Sobre: index.md
 - Planejamento:
   - Metodologia: Planejamento/Metodologia.md
   - Cronograma: Planejamento/Cronograma.md
   - Sites Avaliados: Planejamento/SitesAvaliados.md
 - Processo de design:
    - Usabilidade de Mayhew: ProcessoDesign/UsabilidadeMayhew.md
 - Análise de requisitos: AnaliseRequisitos/arquivo.md
 - Design, Avaliação e Desenvolvimento: DesignAvaliacaoDesenvolvimento/arquivo.md
 - Apresentações:
      - Apresentação 1: Apresentacoes/apresentacao1.md
theme:
  name: material

extra_css: [extra.css]
