site_name: Prefeitura de Passo Fundo
site_url: https://interacao-humano-computador.github.io/2021.2-Prefeitura-de-Passo-Fundo/

# Repository
repo_name: Prefeitura de Passo Fundo 
repo_url: https://github.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo

nav:
 - Sobre: index.md
 - Planejamento:
   - Metodologia: Planejamento/Metodologia.md
   - Cronograma: Planejamento/Cronograma.md
   - Sites Avaliados: Planejamento/SitesAvaliados.md
   - Processo de design:
     - Usabilidade de Mayhew: Planejamento/UsabilidadeMayhew.md
 - Análise de Requisitos:
   - Perfil do usuário:
        - Personas: AnaliseRequisitos/PerfilUsuario/personas.md 
   - Análise de Tarefas: 
       - Análise Hierárquica de Tarefas: AnaliseRequisitos/AnaliseTarefas/hta.md
       - GOMS: AnaliseRequisitos/AnaliseTarefas/goms.md 
   - Princípios Gerais de Projeto: AnaliseRequisitos/PrincipiosProjeto.md 
   - Metas de usabilidade: AnaliseRequisitos/MetasUsabilidade.md 
   - Guia de estilo: AnaliseRequisitos/GuiaEstilo.md 
 - Design, Avaliação e Desenvolvimento: 
   - Nível 1:
        - Análise de Tarefas:
          - Planejamento da avaliação: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
          - Relato da avaliação: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/RelatoAnaliseTarefas.md
        - Storyboard: 
          - Planejamento da avaliação: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/PlanejamentoStoryboard.md
          - Storyboard: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/Storyboard.md
          - Relato da avaliação: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/RelatoStoryboard.md
   - Nível 2: 
       - Protótipo de Baixa Fidelidade: 
           - Planejamento da avaliação: DesignAvaliacaoDesenvolvimento/Nivel2/PlanejamentoProtBaixaFid.md
           - Relato da avaliação: DesignAvaliacaoDesenvolvimento/Nivel2/RelatoProtBaixaFid.md
   - Nível 3:
       - Protótipo de alta Fidelidade: 
           - Planejamento da avaliação: DesignAvaliacaoDesenvolvimento/Nivel3/PlanejamentoProtAltaFid.md
           - Relato da avaliação: DesignAvaliacaoDesenvolvimento/Nivel3/RelatoProtAltaFid.md
 - Verificação: Verificacao/Verificacao.md
 - Apresentações:
      - Apresentação 1: Apresentacoes/apresentacao1.md
      - Apresentação 2: Apresentacoes/apresentacao2.md
      - Apresentação 3: Apresentacoes/apresentacao3.md
      - Apresentação 4: Apresentacoes/apresentacao4.md
 - Atas:
     - Ata 1: Atas/ata1.md
     - Ata 2: Atas/ata2.md 
     - Ata 3: Atas/ata3.md 
theme:
  language: pt
  logo: https://raw.githubusercontent.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo/main/assets/img/logo-passo-fundo.png
  favicon: https://raw.githubusercontent.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo/main/assets/img/logo-passo-fundo.png
  name: material
  palette:
    primary: light green
    accent: green

extra_css: 
  - extra.css
