site_name: Prefeitura de Passo Fundo
site_url: https://interacao-humano-computador.github.io/2021.2-Prefeitura-de-Passo-Fundo/

# Repository
repo_name: Prefeitura de Passo Fundo 
repo_url: https://github.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo

nav:
 - Sobre: index.md
 - Planejamento:
   - Metodologia: Planejamento/Metodologia.md
   - Cronograma: Planejamento/Cronograma.md
   - Sites Avaliados: Planejamento/SitesAvaliados.md
   - Processo de design:
     - Usabilidade de Mayhew: Planejamento/UsabilidadeMayhew.md
 - Análise de Requisitos:
   - Perfil do usuário:
        - Personas: AnaliseRequisitos/PerfilUsuario/personas.md 
   - Análise de Tarefas: 
       - Análise Hierárquica de Tarefas: AnaliseRequisitos/AnaliseTarefas/hta.md
       - Análise Hierárquica de Tarefas V2: AnaliseRequisitos/AnaliseTarefas/htav2.md
       - GOMS: AnaliseRequisitos/AnaliseTarefas/goms.md 
   - Princípios Gerais de Projeto: AnaliseRequisitos/PrincipiosProjeto.md 
   - Metas de usabilidade: AnaliseRequisitos/MetasUsabilidade.md 
   - Guia de estilo: AnaliseRequisitos/GuiaEstilo.md 
 - Design, Avaliação e Desenvolvimento: 
   - Nível 1:
        - Análise de Tarefas:
          - Planejamento da Avaliação da Análise de tarefas: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
          - Relato de resultados da Avaliação da Análise de tarefas: DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/RelatoAnaliseTarefas.md
        - Storyboard: 
          - Planejamento da Avaliação dos Storyboards: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/PlanejamentoStoryboard.md
          - Storyboard: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/Storyboard.md
          - Relato de resultados da Avaliação dos Storyboards: DesignAvaliacaoDesenvolvimento/Nivel1/Storyboard/RelatoStoryboard.md
   - Nível 2: 
       - Protótipo de Papel: 
           - Planejamento da Avaliação do Protótipo de Papel: DesignAvaliacaoDesenvolvimento/Nivel2/PlanejamentoProtBaixaFid.md
           - Relato dos resultados da Avaliação do Protótipo de Papel: DesignAvaliacaoDesenvolvimento/Nivel2/RelatoProtBaixaFid.md
   - Nível 3:
        - Protótipo de alta Fidelidade: 
           - Planejamento da Avaliação do protótipo de alta fidelidade : DesignAvaliacaoDesenvolvimento/Nivel3/PlanejamentoProtAltaFid.md
        ##   - Relato da avaliação: DesignAvaliacaoDesenvolvimento/Nivel3/RelatoProtAltaFid.md
 - Verificação:
        - Planejamento da Verificação: Verificacao/planejamento_verificacao.md
        - Verificação Personas: Verificacao/ver_personas.md
        - Verificação Análise de Tarefas: Verificacao/ver_analise_tarefas.md
        - Verificação Princípios Gerais de Projeto: Verificacao/ver_principios_gerais_projeto.md
        - Verificação Metas de Usabilidade: Verificacao/ver_metas_usabilidade.md
        - Verificação Guia de Estilo: Verificacao/ver_guia_de_estilo.md
        - Verificação Planejamento e relato da avaliação da análise de tarefas: Verificacao/ver_plan_av_tarefas.md
        - Verificação Storyboards: Verificacao/ver_storyboards.md 
        - Verificação Planejamento e relato da avaliação dos Storyboards: Verificacao/ver_plan_av_storyboard.md
       ## - Verificação Protótipo de Papel: Verificacao/ver_prototipo_papel.md
       ## - Verificação Planejamento e relato da Avaliação do Protótipo de Papel: Verificacao/ver_plan_av_prototipo_papel.md
 - Apresentações:
      - Apresentação 1: Apresentacoes/apresentacao1.md
      - Apresentação 2: Apresentacoes/apresentacao2.md
      - Apresentação 3: Apresentacoes/apresentacao3.md
      - Apresentação 4: Apresentacoes/apresentacao4.md
      - Apresentação 5: Apresentacoes/apresentacao5.md
      - Apresentação 6: Apresentacoes/apresentacao6.md
      - Apresentação 7: Apresentacoes/apresentacao7.md
 - Atas:
     - Ata 1: Atas/ata1.md
     - Ata 2: Atas/ata2.md 
     - Ata 3: Atas/ata3.md 
     - Ata 4: Atas/ata4.md 
     - Ata 5: Atas/ata5.md 
     - Ata 6: Atas/ata6.md 
     - Ata 7: Atas/ata7.md
theme:
  language: pt
  logo: https://raw.githubusercontent.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo/main/assets/img/logo-passo-fundo.png
  favicon: https://raw.githubusercontent.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo/main/assets/img/logo-passo-fundo.png
  name: material
  palette:
    primary: light green
    accent: green

extra_css: 
  - extra.css
