site_name: IHC Grupo 2
site_url: https://interacao-humano-computador.github.io/2021.2-Grupo-02/

# Repository
repo_name: 2021.2-Grupo-02 
repo_url: https://github.com/Interacao-Humano-Computador/2021.2-Grupo-02/

nav:
 - Home: index.md
 - Sobre: about.md
 - Planejamento:
   - Cronograma: cronograma.md
   - Avaliações Iniciais: avaliacoes.md
theme:
  name: material
<<<<<<< HEAD

extra_css: [extra.css]
=======
>>>>>>> 760dc0a9ebef5889803c67a0d2940b3fd6f6dde3
